services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://dbuser:admin@postgres:5432/pgtest

  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pgtest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - fastapi

volumes:
  postgres_data: